ARG NODE_VERSION=20
FROM node:${NODE_VERSION}-alpine3.19

RUN apk add build-base git krb5-dev libgit2-dev libssh-dev pkgconfig python3 tzdata

# Ensure C++17 is used explicitly for Node.js 20 and define POSIX features
ENV CXXFLAGS="-std=c++17 -D_GNU_SOURCE"
ENV CFLAGS="-std=c17 -D_GNU_SOURCE -D_POSIX_C_SOURCE=200809L"
ENV JOBS="2"

ADD . /app
WORKDIR /app

RUN npm ci && \
  npx prebuildify --strip --napi=false --tag-libc -t "$(node --version | tr -d 'v')"
