FROM node:20.11.1-alpine3.19

RUN apk add build-base git krb5-dev libgit2-dev libssh-dev pkgconfig python3 tzdata

ADD . /app
WORKDIR /app

RUN npm ci && \
  npx prebuildify --napi --strip --tag-libc -t "$(node --version | tr -d 'v')"
